name: Run Tagged Tests and Publish Report

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag de Cucumber a ejecutar (ej: @smoke, @login)'
        required: true
        default: '@SauceDemo'
      env:
        description: 'Ambiente de ejecución: qa, dev'
        required: true
        default: 'qa'
      email:
        description: 'Correo destinatario del reporte'
        required: true
        default: 'test@example.com'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Validar ambiente
        run: |
          VALID_ENVS="qa dev"
          if [[ ! "$VALID_ENVS" =~ ${{ github.event.inputs.env }} ]]; then
            echo "Ambiente inválido: ${{ github.event.inputs.env }}"
            exit 1
          fi

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Cargar variables de entorno por ambiente
        run: |
          if [ "${{ github.event.inputs.env }}" = "qa" ]; then
            echo "URL_BASE=${{ secrets.URL_BASE_QA }}" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.env }}" = "dev" ]; then
            echo "URL_BASE=${{ secrets.URL_BASE_DEV }}" >> $GITHUB_ENV
          else
            echo "Ambiente inválido: ${{ github.event.inputs.env }}"
            exit 1
          fi

      - name: Run tests by tag and env
        run: npm run test:${{ github.event.inputs.env }} -- --tags "${{ github.event.inputs.tag }}"

      - name: Generate HTML report
        run: node generateReport.js

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: ./reports/html

  deploy-report:
    needs: run-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Download report artifact
        uses: actions/download-artifact@v4
        with:
          name: cucumber-report
          path: ./reports/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: ./reports/html

      - name: Send report by email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: '🧪 Reporte de Pruebas - SauceDemo [${{ github.event.inputs.env }}]'
          to: ${{ github.event.inputs.email }}
          from: ${{ secrets.EMAIL_USERNAME }}
          html_body: |
            <!DOCTYPE html>
            <html lang="es">
            <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Reporte de Pruebas - SauceDemo</title>
              <style>
                body {
                  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
                  line-height: 1.6;
                  color: #333;
                  max-width: 600px;
                  margin: 0 auto;
                  background-color: #f8f9fa;
                }
                .container {
                  background-color: #ffffff;
                  border-radius: 8px;
                  box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                  overflow: hidden;
                  margin: 20px;
                }
                .header {
                  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                  color: white;
                  padding: 30px;
                  text-align: center;
                }
                .header h1 {
                  margin: 0;
                  font-size: 28px;
                  font-weight: 300;
                }
                .content {
                  padding: 30px;
                }
                .info-grid {
                  display: grid;
                  grid-template-columns: 1fr 1fr;
                  gap: 20px;
                  margin: 20px 0;
                }
                .info-card {
                  background-color: #f8f9fa;
                  padding: 20px;
                  border-radius: 6px;
                  border-left: 4px solid #667eea;
                }
                .info-card h3 {
                  margin: 0 0 10px 0;
                  color: #495057;
                  font-size: 14px;
                  text-transform: uppercase;
                  letter-spacing: 1px;
                }
                .info-card p {
                  margin: 0;
                  font-size: 18px;
                  font-weight: 600;
                  color: #212529;
                }
                .cta-section {
                  background-color: #e3f2fd;
                  padding: 25px;
                  text-align: center;
                  border-radius: 6px;
                  margin: 30px 0;
                }
                .cta-button {
                  display: inline-block;
                  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                  color: white;
                  text-decoration: none;
                  padding: 12px 30px;
                  border-radius: 25px;
                  font-weight: 600;
                  font-size: 16px;
                  transition: transform 0.2s;
                }
                .cta-button:hover {
                  transform: translateY(-2px);
                  box-shadow: 0 4px 15px rgba(102, 126, 234, 0.4);
                }
                .footer {
                  background-color: #f8f9fa;
                  padding: 20px;
                  text-align: center;
                  border-top: 1px solid #e9ecef;
                }
                .footer p {
                  margin: 5px 0;
                  color: #6c757d;
                  font-size: 14px;
                }
                .emoji {
                  font-size: 24px;
                  margin-right: 10px;
                }
                @media (max-width: 600px) {
                  .info-grid {
                    grid-template-columns: 1fr;
                  }
                  .container {
                    margin: 10px;
                  }
                }
              </style>
            </head>
            <body>
              <div class="container">
                <div class="header">
                  <h1><span class="emoji">🧪</span>Reporte de Pruebas</h1>
                  <p>Ejecución completada exitosamente</p>
                </div>
                
                <div class="content">
                  <div class="info-grid">
                    <div class="info-card">
                      <h3>🌍 Ambiente</h3>
                      <p>${{ github.event.inputs.env }}</p>
                    </div>
                    <div class="info-card">
                      <h3>🏷️ Tag Ejecutado</h3>
                      <p>${{ github.event.inputs.tag }}</p>
                    </div>
                  </div>
                  
                  <div class="cta-section">
                    <h2 style="margin-top: 0; color: #495057;">📊 Ver Reporte Detallado</h2>
                    <p style="color: #6c757d; margin-bottom: 25px;">
                      Accede al reporte completo con todos los detalles de la ejecución de pruebas
                    </p>
                    <a href="https://esmithas.github.io/SauceDemo-playwright/" class="cta-button">
                      🔗 Ver Reporte
                    </a>
                  </div>
                  
                  <div style="background-color: #fff3cd; border: 1px solid #ffeaa7; border-radius: 6px; padding: 15px; margin: 20px 0;">
                    <p style="margin: 0; color: #856404;">
                      <strong>ℹ️ Información:</strong> Este reporte contiene los resultados de las pruebas automatizadas ejecutadas en el ambiente <strong>${{ github.event.inputs.env }}</strong> con el tag <strong>${{ github.event.inputs.tag }}</strong>.
                    </p>
                  </div>
                </div>
                
                <div class="footer">
                  <p><strong>Autor:</strong> Esmith Sanchez</p>
                  <p><strong>Rol:</strong> QE Automation Engineer</p>
                  <p style="font-size: 12px; color: #adb5bd;">
                    Generado automáticamente por GitHub Actions
                  </p>
                </div>
              </div>
            </body>
            </html>
